# Generated by Django 5.1.4 on 2025-03-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('adr', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=32)),
                ('pin', models.IntegerField()),
                ('gst', models.CharField(max_length=15)),
                ('contact', models.CharField(max_length=64)),
                ('bank_ifsc', models.CharField(max_length=11)),
            ],
        ),
    ]
