# Generated by Django 5.1.7 on 2025-07-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buyer',
            fields=[
                ('buyerId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('adr1', models.CharField(max_length=128, null=True)),
                ('adr2', models.CharField(max_length=128, null=True)),
                ('state', models.CharField(max_length=32)),
                ('pin', models.IntegerField()),
                ('gstin', models.CharField(max_length=15)),
            ],
        ),
    ]
