# Generated by Django 5.1.4 on 2025-01-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buyer',
            fields=[
                ('buyerID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('adr', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=32)),
                ('pin', models.IntegerField()),
                ('gst', models.CharField(max_length=15)),
            ],
        ),
    ]
