# Generated by Django 5.1.7 on 2025-03-08 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='buyerID',
            new_name='buyer_id',
        ),
    ]
