# Generated by Django 5.1.7 on 2025-07-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='adr1',
            field=models.CharField(default='null', max_length=128),
            preserve_default=False,
        ),
    ]
