# Generated by Django 5.1.7 on 2025-07-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_alter_buyer_adr1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='pin',
            field=models.CharField(max_length=10),
        ),
    ]
