# Generated by Django 5.1.7 on 2025-07-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('adr1', models.CharField(max_length=128)),
                ('adr2', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128)),
                ('pin', models.IntegerField()),
                ('gstin', models.CharField(max_length=15)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
                ('bankName', models.CharField(max_length=64)),
                ('bankAcc', models.CharField(max_length=32)),
                ('bandIfsc', models.CharField(max_length=32)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='asset/')),
            ],
        ),
    ]
