# Generated by Django 5.1.7 on 2025-08-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_remove_userprofile_id_userprofile_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='userId',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
