# Generated by Django 5.1.7 on 2025-08-04 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_rename_userprofile_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bandIfsc',
            new_name='bankIfsc',
        ),
    ]
