# Generated by Django 5.1.7 on 2025-07-25 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invId', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('buyerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buyer.buyer')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=64)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst', models.DecimalField(decimal_places=2, max_digits=5)),
                ('qty', models.IntegerField(default=1)),
                ('invId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
            ],
        ),
    ]
