# Generated by Django 5.1.4 on 2025-02-16 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('invID', models.AutoField(primary_key=True, serialize=False)),
                ('buyerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buyer.buyer')),
            ],
        ),
    ]
