# Generated by Django 5.1.7 on 2025-07-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invNum',
            field=models.CharField(default='null', max_length=32),
            preserve_default=False,
        ),
    ]
