# Generated by Django 5.1.7 on 2025-07-28 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_alter_buyer_pin'),
        ('invoice', '0002_invoice_invnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='grandTotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='gstTotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subTotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='buyerId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buyer.buyer'),
        ),
        migrations.AlterField(
            model_name='items',
            name='invId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_set', to='invoice.invoice'),
        ),
    ]
