# Generated by Django 5.1.4 on 2025-02-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
