# Generated by Django 5.1.7 on 2025-07-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoice_grandtotal_invoice_gsttotal_invoice_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='gst',
            field=models.DecimalField(decimal_places=2, default=18, max_digits=5),
        ),
    ]
