# Generated by Django 5.1.7 on 2025-08-04 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_alter_items_gst'),
        ('user_profile', '0005_rename_userprofile_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='userId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_profile.profile'),
        ),
    ]
