# Generated by Django 5.1.7 on 2025-03-08 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_invoice_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='buyerID',
            new_name='buyer_id',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='invID',
            new_name='inv_id',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='invID',
            new_name='inv_id',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='itemName',
            new_name='item_name',
        ),
    ]
